=== Bojo38/tourma/src/bb/teamma/rules/lrb6/roster.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="skillType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="accronym" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:element name="skill">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="category" type="skillType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SkillList">  
        <xs:sequence>  
            <xs:element name="skill" type="skill" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType> 
  
    <xs:complexType name="SkillTypeList">  
        <xs:sequence>  
            <xs:element name="skillType" type="skillType" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType> 
    
    <xs:element name="playerType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="limit" type="xs:integer" />
                <xs:element name="position" type="xs:string" />
                <xs:element name="movement" type="xs:integer" />
                <xs:element name="strength" type="xs:integer" />
                <xs:element name="agility" type="xs:integer" />
                <xs:element name="armor" type="xs:integer" />
                <xs:element name="skills" type="SkillList" />
                <xs:element name="cost" type="xs:integer" />
                <xs:element name="single" type="SkillTypeList" />
                <xs:element name="double" type="SkillTypeList" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="starplayer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="position" type="xs:string" />
                <xs:element name="movement" type="xs:integer" />
                <xs:element name="stength" type="xs:integer" />
                <xs:element name="agility" type="xs:integer" />
                <xs:element name="armor" type="xs:integer" />
                <xs:element name="skills" type="SkillList" />
                <xs:element name="cost" type="xs:integer" />
                <xs:sequence>  
                    <xs:element name="team" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>  
                </xs:sequence>  
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="PlayerTypeList">  
        <xs:sequence>  
            <xs:element name="playertype" type="playerType" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType>
  
    <xs:complexType name="StarPlayerList">  
        <xs:sequence>  
            <xs:element name="starplayer" type="starplayer" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType>
    
    <xs:element name="rostertype">
        <xs:complexType>
            <xs:sequence>                
                <xs:element name="playertypes" type="PlayerTypeList" />
                <xs:element name="name" type="xs:string" />
                <xs:element name="reroll" type="xs:integer" />
                <xs:element name="apothecary" type="xs:integer" />
                <xs:element name="chef" type="xs:integer" />
                <xs:element name="igor" type="xs:integer" />
                <xs:element name="bribe" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
            
</xs:schema>

=== Bojo38/tourma/src/bb/teamma/rules/BB2020/chaos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>ChaosChosenKey</name>
    <reroll>60000</reroll>
    <apothecary>true</apothecary>
    <max_big_guy>1</max_big_guy>
   <!--Favorite Of Nurgle -->
    <inducements>
        <inducement name="temp agency cheerleaders" max="4" cost="20000" />
        <inducement name="part time assistant coaches" max="3" cost="20000" />
        <inducement name="weather mage" max="1" cost="30000" />
        <inducement name="Bloodweisers kegs" max="2" cost="50000" />
        <inducement name="special plays" max="5" cost="100000" />
        <inducement name="extra team training" max="8" cost="100000" />
        <inducement name="bribes" max="3" cost="100000" />
        <inducement name="wandering apothecary" max="2" cost="100000" />
        <!--<inducement name="mortuary assistant" max="1" cost="300000" />-->
        <inducement name="plague doctor" max="1" cost="100000" />
        <!--<inducement name="riotous rookies" max="1" cost="100000" />-->  
        <inducement name="halfling master chef" max="1" cost="300000" />
       
        <inducement name="Joseph Bugman" max="1" cost="100000" />
        <inducement name="wizard" max="1" cost="150000" />  
        <inducement name="Biased referee" max="1" cost="120000" />
    </inducements>
            
    <playertypes>               
        <playerType>
            <limit>4</limit>
            <position>Chosen Blocker</position>
            <movement>5</movement>
            <strength>4</strength>
            <agility>3</agility>
            <pass>5</pass>
            <armor>10</armor>
            <skills>
            </skills>
            <cost>100000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Beastman Runner Linemen</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <pass>4</pass>
            <armor>9</armor>
            <skills>
                <skill>Horns</skill>              
            </skills>
            <cost>60000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Chaos Troll</position>
            <movement>4</movement>
            <strength>5</strength>
            <agility>5</agility>
            <pass>5</pass>
            <armor>10</armor>
            <skills>
                <skill>Always Hungry</skill>
                <skill>Loner (4+)</skill>
                <skill>Mighty Blow (+1)</skill>
                <skill>Projectile Vomit</skill>
                <skill>Really Stupid</skill>
                <skill>Regeneration</skill>
                <skill>Throw Team-Mate</skill>
                <skill>Big Guy</skill>     
            </skills>
            <cost>115000</cost>
            <single>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Chaos Ogre</position>
            <movement>5</movement>
            <strength>5</strength>
            <agility>4</agility>
            <pass>5</pass>
            <armor>10</armor>
            <skills>
                <skill>Bone Head</skill>
                <skill>Thick Skull</skill>
                <skill>Loner (4+)</skill>
                <skill>Mighty Blow (+1)</skill>
                <skill>Throw Team-Mate</skill>
                <skill>Big Guy</skill>             
            </skills>
            <cost>140000</cost>
            <single>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Minotaur</position>
            <movement>5</movement>
            <strength>5</strength>
            <agility>4</agility>
            <pass>-1</pass>
            <armor>9</armor>
            <skills>
                <skill>Loner (4+)</skill>
                <skill>Frenzy</skill>
                <skill>Horns</skill>  
                <skill>Mighty Blow (+1)</skill>                  
                <skill>Thick Skull</skill>               
                <skill>Unchannelled Fury</skill>  
                <skill>Big Guy</skill>          
            </skills>
            <cost>150000</cost>
            <single>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/lrb2/halflings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>
    <inducements></inducements>
    <name>HalflingKey</name>
    <reroll>60000</reroll>
    <apothecary>true</apothecary>
    <chef>100000</chef>
    <igor>false</igor>
    <bribe>100000</bribe>
    <max_big_guy>2</max_big_guy>
    <playertypes>               
        <playerType>
            <limit>2</limit>
            <position>Treeman</position>
            <movement>2</movement>
            <strength>6</strength>
            <agility>1</agility>
            <armor>10</armor>
            <skills>
                <skill>Take Roots</skill>
                <skill>Stand Firm</skill>
                <skill>Mighty Blow</skill>
                <skill>Thick Skull</skill>
                <skill>Big Guy</skill>
                <skill>Throw Team-Mate</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>Strength Trait</skillType>
                <skillType>General Skill</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>Agility Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Halflings</position>
            <movement>5</movement>
            <strength>2</strength>
            <agility>3</agility>
            <armor>6</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Stunty</skill>
                <skill>Right Stuff</skill>
            </skills>
            <cost>30000</cost>
            <single>               
                <skillType>Agility Skill</skillType>
            </single>
            <double>
                <skillType>Agility Trait</skillType>
                <skillType>General Skill</skillType>
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Ogre</position>
            <movement>5</movement>
            <strength>5</strength>
            <agility>2</agility>
            <armor>9</armor>
            <skills>
                <skill>Bone Head</skill>
                <skill>Mighty Blow</skill>
                <skill>Thick Skull</skill>
                <skill>Throw Team-Mate</skill>
                <skill>Big Guy</skill>
            </skills>
            <cost>120000</cost>
            <single>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>General Skill</skillType>
                <skillType>Strength Trait</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>Agility Skill</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/naf2017/necromantics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>NecromanticHorrorKey</name>
    <reroll>70000</reroll>
    <apothecary>false</apothecary>
    <chef>300000</chef>
    <igor>true</igor>
    <bribe>100000</bribe>
    <playertypes>               
        <playerType>
            <limit>2</limit>
            <position>Werewolf</position>
            <movement>8</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Frenzy</skill>
                <skill>Regeneration</skill>
                <skill>Claws</skill>
            </skills>
            <cost>120000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Ghoul</position>
            <movement>7</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Dodge</skill>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
             <limit>2</limit>
            <position>Wight</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Block</skill>
                <skill>Regeneration</skill>
            </skills>
            <cost>90000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Flesh Golem</position>
            <movement>4</movement>
            <strength>4</strength>
            <agility>2</agility>
            <armor>9</armor>
            <skills>
                <skill>Stand Firm</skill>
                <skill>Regeneration</skill>
                <skill>Thick Skull</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Zombie</position>
            <movement>4</movement>
            <strength>3</strength>
            <agility>2</agility>
            <armor>8</armor>
            <skills>
                <skill>Regeneration</skill>
            </skills>
            <cost>40000</cost>
            <single>
                <skillType>General</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/tourma/src/teamma/rules/vampires.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>Vampires</name>
    <reroll>70000</reroll>
    <apothecary>false</apothecary>
    <chef>300000</chef>
    <igor>true</igor>
    <bribe>100000</bribe>
    <playertypes>               
        <playerType>
            <limit>6</limit>
            <position>Vampires</position>
            <movement>6</movement>
            <strength>4</strength>
            <agility>4</agility>
            <armor>8</armor>
            <skills>
                <skill>Regeneration</skill>
                <skill>Hypnotic Gaze</skill>
                <skill>Blood Lust</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Thrall</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
            </skills>
            <cost>40000</cost>
            <single>
                <skillType>General</skillType>                
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
                <skillType>Strength</skillType>
            </double>
        </playerType>       
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/bb/teamma/rules/BB2020/woodelves.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>WoodElfKey</name>
    <reroll>50000</reroll>
    <apothecary>true</apothecary>
    <max_big_guy>1</max_big_guy>
    <inducements>
        <inducement name="chef" max="1" cost="300000" />
        <inducement name="bribe the ref" max="3" cost="100000" />
        <inducement name="Bloodweisers' babes" max="2" cost="50000" />
        <inducement name="wizard" max="1" cost="150000" />
        <inducement name="extra reroll" max="4" cost="100000" />
        <inducement name="local apothecary" max="1" cost="100000" />
        <inducement name="cards" max="8" cost="50000" />
        <inducement name="specialist assistant coaches" max="5" cost="20000" />
        <inducement name="temp agency cheerleaders" max="5" cost="20000" />
        <inducement name="weather mage" max="1" cost="30000" />
        <inducement name="Horatio X Schottenheim" max="1" cost="80000" />
        <inducement name="Galandril Silverwater" max="1" cost="50000" />
    </inducements>
    <playertypes>               
        <playerType>
            <limit>2</limit>
            <position>Wardancer</position>
            <movement>8</movement>
            <strength>3</strength>
            <agility>2</agility>
            <pass>4</pass>
            <armor>8</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Block</skill>
                <skill>Leap</skill>
            </skills>
            <cost>125000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>            
                <skillType>Strength</skillType>
            </double>
        </playerType>
        
        <playerType>
            <limit>2</limit>
            <position>Thrower</position>
            <movement>7</movement>
            <strength>3</strength>
            <agility>2</agility>
            <pass>2</pass>
            <armor>8</armor>
            <skills>
                <skill>Pass</skill>
            </skills>
            <cost>95000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>4</limit>
            <position>Catcher</position>
            <movement>8</movement>
            <strength>2</strength>
            <agility>2</agility>
            <pass>4</pass>
            <armor>8</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Catch</skill>
            </skills>
            <cost>90000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>12</limit>
            <position>Wood Elf Lineman</position>
            <movement>7</movement>
            <strength>3</strength>
           <agility>2</agility>
            <pass>4</pass>
            <armor>8</armor>
            <skills>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Loren Forest Treeman</position>
            <movement>2</movement>
            <strength>6</strength>
            <agility>5</agility>
            <pass>5</pass>
            <armor>11</armor>
            <skills>
                  <skill>Take Roots</skill>
                  <skill>Loner (4+)</skill>
                  <skill>Stand Firm</skill>
                  <skill>Mighty Blow (+1)</skill>
                  <skill>Thick Skull</skill>
                  <skill>Strong Arm</skill>
                  <skill>Throw Team-Mate</skill>
                  <skill>Big Guy</skill>
            </skills>
            <cost>120000</cost>
            <single>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/bb/teamma/rules/BB2016/darkelves.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>DarkElfKey</name>
    <reroll>50000</reroll>
    <apothecary>true</apothecary>
    
    <inducements>
        <inducement name="chef" max="1" cost="300000" />
        <inducement name="bribe the ref" max="3" cost="100000" />
        <inducement name="Bloodweisers' babes" max="2" cost="50000" />
        <inducement name="wizard" max="1" cost="150000" />
        <inducement name="extra reroll" max="4" cost="100000" />
        <inducement name="local apothecary" max="1" cost="100000" />
        <inducement name="cards" max="8" cost="50000" />
        <inducement name="specialist assistant coaches" max="5" cost="20000" />
        <inducement name="temp agency cheerleaders" max="5" cost="20000" />
        <inducement name="weather mage" max="1" cost="30000" />
        <inducement name="Druchii sports sorceress" max="1" cost="150000" />
        <inducement name="Horatio X Schottenheim" max="1" cost="80000" />
    </inducements>   
    
    <playertypes>               
        <playerType>
            <limit>4</limit>
            <position>Blitzer</position>
            <movement>7</movement>
            <strength>3</strength>
            <agility>4</agility>
            <armor>8</armor>
            <skills>
                <skill>Block</skill>
            </skills>
            <cost>100000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Strength</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Witch Elf</position>
            <movement>7</movement>
            <strength>3</strength>
            <agility>4</agility>
            <armor>7</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Frenzy</skill>
                <skill>Jump Up</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Runner</position>
            <movement>7</movement>
            <strength>3</strength>
            <agility>4</agility>
            <armor>7</armor>
            <skills>
                <skill>Dump-Off</skill>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
            </double>
        </playerType>
         <playerType>
            <limit>2</limit>
            <position>Assassin</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>4</agility>
            <armor>7</armor>
            <skills>
                <skill>Stab</skill>
                <skill>Shadowing</skill>
            </skills>
            <cost>90000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>   
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Lineman</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>4</agility>
            <armor>8</armor>
            <skills>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>            
            </double>
        </playerType>
    </playertypes>
</rostertype>
