=== Bojo38/tourma/src/bb/teamma/rules/lrb6/roster.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="skillType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="accronym" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:element name="skill">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="category" type="skillType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SkillList">  
        <xs:sequence>  
            <xs:element name="skill" type="skill" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType> 
  
    <xs:complexType name="SkillTypeList">  
        <xs:sequence>  
            <xs:element name="skillType" type="skillType" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType> 
    
    <xs:element name="playerType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="limit" type="xs:integer" />
                <xs:element name="position" type="xs:string" />
                <xs:element name="movement" type="xs:integer" />
                <xs:element name="strength" type="xs:integer" />
                <xs:element name="agility" type="xs:integer" />
                <xs:element name="armor" type="xs:integer" />
                <xs:element name="skills" type="SkillList" />
                <xs:element name="cost" type="xs:integer" />
                <xs:element name="single" type="SkillTypeList" />
                <xs:element name="double" type="SkillTypeList" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="starplayer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="position" type="xs:string" />
                <xs:element name="movement" type="xs:integer" />
                <xs:element name="stength" type="xs:integer" />
                <xs:element name="agility" type="xs:integer" />
                <xs:element name="armor" type="xs:integer" />
                <xs:element name="skills" type="SkillList" />
                <xs:element name="cost" type="xs:integer" />
                <xs:sequence>  
                    <xs:element name="team" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>  
                </xs:sequence>  
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="PlayerTypeList">  
        <xs:sequence>  
            <xs:element name="playertype" type="playerType" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType>
  
    <xs:complexType name="StarPlayerList">  
        <xs:sequence>  
            <xs:element name="starplayer" type="starplayer" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType>
    
    <xs:element name="rostertype">
        <xs:complexType>
            <xs:sequence>                
                <xs:element name="playertypes" type="PlayerTypeList" />
                <xs:element name="name" type="xs:string" />
                <xs:element name="reroll" type="xs:integer" />
                <xs:element name="apothecary" type="xs:integer" />
                <xs:element name="chef" type="xs:integer" />
                <xs:element name="igor" type="xs:integer" />
                <xs:element name="bribe" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
            
</xs:schema>

=== Bojo38/tourma/src/teamma/rules/lrb3/norses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>
    <inducements></inducements>
    <name>NorseKey</name>
    <reroll>60000</reroll>
    <apothecary>true</apothecary>
    <chef>300000</chef>
    <igor>false</igor>
    <bribe>100000</bribe>
    <max_big_guy>1</max_big_guy>
    <playertypes>               
        <playerType>
            <limit>4</limit>
            <position>Blitzer</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Block</skill>
                <skill>Jump Up</skill>
                <skill>Frenzy</skill>
            </skills>
            <cost>90000</cost>
            <single>
                <skillType>General Skill</skillType>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Strength Trait</skillType>
                <skillType>Agility Skill</skillType>
                <skillType>Pass Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Catcher</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Block</skill>
                <skill>Catch</skill>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General Skill</skillType>
                <skillType>Agility Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Agility Trait</skillType>
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>                
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Thrower</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Block</skill>
                <skill>Pass</skill>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General Skill</skillType>
                <skillType>Pass Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Pass Trait</skillType>
                <skillType>Strength Skill</skillType>
                <skillType>Agility Skill</skillType>                
            </double>
        </playerType>
        <playerType>
            <limit>12</limit>
            <position>Lineman</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Block</skill>
            </skills>
            <cost>50000</cost>
            <single>
                <skillType>General Skill</skillType>                
            </single>
            <double>
                <skillType>General Trait</skillType>                
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>   
                <skillType>Agility Skill</skillType>             
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Minotaur</position>
            <movement>5</movement>
            <strength>5</strength>
            <agility>2</agility>
            <armor>8</armor>
            <skills>
                <skill>Big Guy</skill>
                <skill>Wild Animal</skill>
                <skill>Mighty Blow</skill>
                <skill>Thick Skull</skill>
                <skill>Frenzy</skill>
                <skill>Horns</skill>
                <skill>Always Hungry</skill>
                <skill>Throw Team-Mate</skill>              
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>Strength Trait</skillType>
                <skillType>Physical Trait</skillType>
                <skillType>General Skill</skillType>
                <skillType>Agility Skill</skillType>
                <skillType>Pass Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Ogre</position>
            <movement>5</movement>
            <strength>5</strength>
            <agility>2</agility>
            <armor>9</armor>
            <skills>
                <skill>Bone Head</skill>
                <skill>Mighty Blow</skill>
                <skill>Thick Skull</skill>
                <skill>Throw Team-Mate</skill>
                <skill>Big Guy</skill>
            </skills>
            <cost>120000</cost>
            <single>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>Strength Trait</skillType>
                <skillType>General Skill</skillType>                
                <skillType>Pass Skill</skillType>
                <skillType>Agility Skill</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/tourma/src/teamma/rules/nurgle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>NurgleKey</name>
    <reroll>70000</reroll>
    <apothecary>false</apothecary>
    <chef>300000</chef>
    <igor>true</igor>
    <bribe>100000</bribe>
    <playertypes>               
        <playerType>
            <limit>4</limit>
            <position>Nurgle's Warrior</position>
            <movement>4</movement>
            <strength>4</strength>
            <agility>2</agility>
            <armor>9</armor>
            <skills>
                <skill>Disturbing Presence</skill>
                <skill>Foul Appearance</skill>
                <skill>Nurgle's Rot</skill>
                <skill>Regeneration</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>4</limit>
            <position>Pestigor</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Horns</skill>
                <skill>Nurgle's Rot</skill>
                <skill>Regeneration</skill>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Nurgle's Beast</position>
            <movement>4</movement>
            <strength>5</strength>
            <agility>1</agility>
            <armor>9</armor>
            <skills>
                <skill>Disturbing Presence</skill>
                <skill>Foul Appearance</skill>
                <skill>Nurgle's Rot</skill>
                <skill>Regeneration</skill>
                <skill>Loner</skill>
                <skill>Really Stupid</skill>
                <skill>Tentacles</skill>
                <skill>Mighty Blow</skill>
            </skills>
            <cost>140000</cost>
            <single>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Rotter</position>
            <movement>5</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Nurgle's Rot</skill>
                <skill>Decay</skill>
            </skills>
            <cost>40000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/bb/teamma/rules/BB2020/dwarves.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>DwarfKey</name>
    <reroll>50000</reroll>
    <apothecary>true</apothecary>
    <max_big_guy>0</max_big_guy>
    <inducements>
        <inducement name="chef" max="1" cost="300000" />
        <inducement name="bribe the ref" max="3" cost="100000" />
        <inducement name="Bloodweisers' babes" max="2" cost="50000" />
        <inducement name="wizard" max="1" cost="150000" />
        <inducement name="extra reroll" max="4" cost="100000" />
        <inducement name="local apothecary" max="1" cost="100000" />
        <inducement name="cards" max="8" cost="50000" />
        <inducement name="specialist assistant coaches" max="5" cost="20000" />
        <inducement name="temp agency cheerleaders" max="5" cost="20000" />
        <inducement name="weather mage" max="1" cost="30000" />
        <inducement name="Horatio X Schottenheim" max="1" cost="80000" />
        <inducement name="Kari Coldsteal" max="1" cost="50000" />
        <inducement name="Joseph Bugman" max="1" cost="70000" />
    </inducements>  
    
    
    <playertypes>               
        <playerType>
            <limit>2</limit>
            <position>Troll Slayer</position>
            <movement>5</movement>
            <strength>3</strength>
            <agility>4</agility>
            <pass>-1</pass>
            <armor>9</armor>
            <skills>
                <skill>Dauntless</skill>
                <skill>Block</skill>
                <skill>Frenzy</skill>
                <skill>Thick Skull</skill>
            </skills>
            <cost>95000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        
        <playerType>
            <limit>2</limit>
            <position>Blitzer</position>
            <movement>5</movement>
            <strength>3</strength>
            <agility>3</agility>
             <pass>4</pass>
            <armor>10</armor>
            <skills>
                <skill>Block</skill>
                <skill>Thick Skull</skill>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        
        <playerType>
            <limit>2</limit>
            <position>Runner</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <pass>4</pass>
            <armor>9</armor>
            <skills>
                <skill>Sure Hands</skill>
                <skill>Thick Skull</skill>
            </skills>
            <cost>85000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        
        <playerType>
            <limit>12</limit>
            <position>Blocker</position>
            <movement>4</movement>
            <strength>3</strength>
            <agility>4</agility>
             <pass>5</pass>
            <armor>10</armor>
            <skills>
                <skill>Block</skill>
                <skill>Tackle</skill>
                <skill>Thick Skull</skill>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Deathroller</position>
            <movement>4</movement>
            <strength>7</strength>
            <agility>5</agility>
            <pass>-1</pass>
            <armor>11</armor>
            <skills>
                <skill>Loner (5+)</skill>
                <skill>Secret Weapon</skill>
                <skill>No Hand</skill>
                <skill>Mighty Blow (+1)</skill>
                <skill>Break Tackle</skill>
                <skill>Dirty Player (+2)</skill>
                <skill>Juggernaut</skill>
                <skill>Stand Firm</skill>
            </skills>
            <cost>170000</cost>
            <single>                
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/lrb6/khornesdaemons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>KhornesDaemonsKey</name>
    <reroll>70000</reroll>
    <apothecary>true</apothecary>
    <chef>300000</chef>
    <igor>false</igor>
    <bribe>100000</bribe>
    <playertypes>               
        <playerType>
            <limit>1</limit>
            <position>Bloodt hirster</position>
            <movement>6</movement>
            <strength>5</strength>
            <agility>1</agility>
            <armor>9</armor>
            <skills>
                <skill>Loner</skill>
                <skill>Wild Animal</skill>
                <skill>Juggernaut</skill>
                <skill>Frenzy</skill>
                <skill>Claw</skill>
                <skill>Regeneration</skill>
                <skill>Horns</skill>
            </skills>
            <cost>180000</cost>
            <single>                
                <skillType>Strength</skillType>                
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Khorne Herald</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Horns</skill>
                <skill>Frenzy</skill>
                <skill>Juggernaut</skill>
            </skills>
            <cost>90000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>                
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>4</limit>
            <position>Bloodletter daemon</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Horns</skill>
                <skill>Juggernaut</skill>
                <skill>Regeneration</skill>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>                
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Pit Fighter</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Frenzy</skill>
            </skills>
            <cost>50000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>                
                <skillType>Agility</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/lrb1/lizardmen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>
 <inducements>
        <inducement name="wizard" max="1" cost="50000"/>
    </inducements>
    <name>LizardmenKey</name>
    <reroll>60000</reroll>
    <apothecary>true</apothecary>
    <max_big_guy>1</max_big_guy>
    <playertypes>               
        <playerType>
            <limit>6</limit>
            <position>Saurus</position>
            <movement>6</movement>
            <strength>4</strength>
            <agility>1</agility>
            <armor>9</armor>
            <skills>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General Skill</skillType>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Strength Trait</skillType>
                <skillType>Agility Skill</skillType>
                <skillType>Pass Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Skink</position>
            <movement>8</movement>
            <strength>2</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Stunty</skill>
            </skills>
            <cost>60000</cost>
            <single>                
                <skillType>Agility Skill</skillType>
            </single>
            <double>
                <skillType>Agility Trait</skillType>
                <skillType>General Skill</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>Strength Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Kroxigor</position>
            <movement>6</movement>
            <strength>5</strength>
            <agility>1</agility>
            <armor>9</armor>
            <skills>
                <skill>Bone Head</skill>
                <skill>Thick Skull</skill>
                <skill>Prehensile Tail</skill>
                <skill>Big Guy</skill>
            </skills>
            <cost>130000</cost>
            <single>
                <skillType>Strength Skill</skillType>                
            </single>
            <double>
                <skillType>Strength Trait</skillType>                
                <skillType>General Skill</skillType>
                <skillType>Agility Skill</skillType>
                <skillType>Pass Skill</skillType>
            </double>
        </playerType>     
    </playertypes>
</rostertype>
