=== Bojo38/tourma/src/bb/teamma/rules/lrb6/roster.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="skillType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="accronym" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:element name="skill">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="category" type="skillType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="SkillList">  
        <xs:sequence>  
            <xs:element name="skill" type="skill" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType> 
  
    <xs:complexType name="SkillTypeList">  
        <xs:sequence>  
            <xs:element name="skillType" type="skillType" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType> 
    
    <xs:element name="playerType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="limit" type="xs:integer" />
                <xs:element name="position" type="xs:string" />
                <xs:element name="movement" type="xs:integer" />
                <xs:element name="strength" type="xs:integer" />
                <xs:element name="agility" type="xs:integer" />
                <xs:element name="armor" type="xs:integer" />
                <xs:element name="skills" type="SkillList" />
                <xs:element name="cost" type="xs:integer" />
                <xs:element name="single" type="SkillTypeList" />
                <xs:element name="double" type="SkillTypeList" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="starplayer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="position" type="xs:string" />
                <xs:element name="movement" type="xs:integer" />
                <xs:element name="stength" type="xs:integer" />
                <xs:element name="agility" type="xs:integer" />
                <xs:element name="armor" type="xs:integer" />
                <xs:element name="skills" type="SkillList" />
                <xs:element name="cost" type="xs:integer" />
                <xs:sequence>  
                    <xs:element name="team" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>  
                </xs:sequence>  
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="PlayerTypeList">  
        <xs:sequence>  
            <xs:element name="playertype" type="playerType" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType>
  
    <xs:complexType name="StarPlayerList">  
        <xs:sequence>  
            <xs:element name="starplayer" type="starplayer" minOccurs="0" maxOccurs="unbounded"/>  
        </xs:sequence>  
    </xs:complexType>
    
    <xs:element name="rostertype">
        <xs:complexType>
            <xs:sequence>                
                <xs:element name="playertypes" type="PlayerTypeList" />
                <xs:element name="name" type="xs:string" />
                <xs:element name="reroll" type="xs:integer" />
                <xs:element name="apothecary" type="xs:integer" />
                <xs:element name="chef" type="xs:integer" />
                <xs:element name="igor" type="xs:integer" />
                <xs:element name="bribe" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
            
</xs:schema>

=== Bojo38/tourma/src/bb/teamma/rules/lrb5/orcs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>
    <inducements>
        <inducement name="chef" max="1" cost="300000" />
        <inducement name="bribe the ref" max="3" cost="100000" />
        <inducement name="Bloodweisers' babes" max="2" cost="50000" />
        <inducement name="wizard" max="1" cost="150000" />
        <inducement name="extra reroll" max="4" cost="100000" />
        <inducement name="local apothecary" max="1" cost="100000" />
        <inducement name="cards" max="8" cost="50000" />
     </inducements>
    <name>OrcKey</name>
    <reroll>60000</reroll>
    <apothecary>true</apothecary>
    <chef>300000</chef>
    <igor>false</igor>
    <bribe>100000</bribe>
    <playertypes>               
        <playerType>
            <limit>4</limit>
            <position>Blitzer</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>9</armor>
            <skills>
                <skill>Block</skill>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>4</limit>
            <position>Black Orc Blocker</position>
            <movement>4</movement>
            <strength>4</strength>
            <agility>2</agility>
            <armor>9</armor>
            <skills>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>                
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>4</limit>
            <position>Goblin</position>
            <movement>6</movement>
            <strength>2</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Stunty</skill>
                <skill>Right Stuff</skill>
            </skills>
            <cost>40000</cost>
            <single>               
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Lineman</position>
            <movement>5</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>9</armor>
            <skills>
            </skills>
            <cost>50000</cost>
            <single>
                <skillType>General</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
         <playerType>
            <limit>2</limit>
            <position>Thrower</position>
            <movement>5</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Sure Hands</skill>
                <skill>Pass</skill>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
            </single>
            <double>
                <skillType>Strength</skillType>                
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Troll</position>
            <movement>4</movement>
            <strength>5</strength>
            <agility>1</agility>
            <armor>9</armor>
            <skills>
                <skill>Loner</skill>
                <skill>Really Stupid</skill>
                <skill>Always Hungry</skill>
                <skill>Mighty Blow</skill>
                <skill>Regeneration</skill>
                <skill>Throw Team-Mate</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/bb/teamma/rules/lrb5/lizardmen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>
    <inducements>
        <inducement name="chef" max="1" cost="300000" />
        <inducement name="bribe the ref" max="3" cost="100000" />
        <inducement name="Bloodweisers' babes" max="2" cost="50000" />
        <inducement name="wizard" max="1" cost="150000" />
        <inducement name="extra reroll" max="4" cost="100000" />
        <inducement name="local apothecary" max="1" cost="100000" />
        <inducement name="cards" max="8" cost="50000" />
     </inducements>
    <name>LizardmenKey</name>
    <reroll>60000</reroll>
    <apothecary>true</apothecary>
    <chef>300000</chef>
    <igor>false</igor>
    <bribe>100000</bribe>
    <playertypes>               
        <playerType>
            <limit>6</limit>
            <position>Saurus</position>
            <movement>6</movement>
            <strength>4</strength>
            <agility>1</agility>
            <armor>9</armor>
            <skills>
            </skills>
            <cost>80000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Skink</position>
            <movement>8</movement>
            <strength>2</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Stunty</skill>
            </skills>
            <cost>60000</cost>
            <single>
                
                <skillType>Agility</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
                <skillType>Strength</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Kroxigor</position>
            <movement>6</movement>
            <strength>5</strength>
            <agility>1</agility>
            <armor>9</armor>
            <skills>
                <skill>Loner</skill>
                <skill>Mighty Blow</skill>
                <skill>Bone Head</skill>
                <skill>Thick Skull</skill>
                <skill>Prehensile Tail</skill>
            </skills>
            <cost>140000</cost>
            <single>
                <skillType>Strength</skillType>                
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>     
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/lrb4/ogres.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>
    <inducements></inducements>
    <name>OgreKey</name>
    <reroll>70000</reroll>
    <apothecary>true</apothecary>
    <chef>300000</chef>
    <igor>false</igor>
    <bribe>100000</bribe>
    
    <playertypes>               
         <playerType>
            <limit>12</limit>
            <position>Ogre</position>
            <movement>5</movement>
            <strength>5</strength>
            <agility>2</agility>
            <armor>9</armor>
            <skills>
                <skill>Bone Head</skill>
                <skill>Mighty Blow</skill>
                <skill>Thick Skull</skill>
                <skill>Throw Team-Mate</skill>
            </skills>
            <cost>120000</cost>
            <single>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>Strength Trait</skillType>
                <skillType>General Skill</skillType>                
                <skillType>Pass Skill</skillType>
                <skillType>Agility Skill</skillType>
            </double>
        </playerType>
        
        <playerType>
            <limit>6</limit>
            <position>Goblin</position>
            <movement>6</movement>
            <strength>2</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Dodge</skill>
                <skill>Right Stuff</skill>
                <skill>Stunty</skill>
            </skills>
            <cost>40000</cost>
            <single>
                <skillType>Agility Skill</skillType>                
            </single>
            <double>
                <skillType>Agility Trait</skillType>                
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>General Skill</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/BB2016/bretonians.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>BretonianKey</name>
    <reroll>70000</reroll>
    <apothecary>true</apothecary>
    
    <chef>300000</chef>
    <bribe>100000</bribe>
    
    <inducements>
        <chef>300000</chef>
        <bribe>100000</bribe>
        <babes>50000</babes>
        <wizard>150000</wizard>
        <reroll>100000</reroll>
        <apothecary>100000</apothecary>

        <cards>yes</cards>
        <starplayers>yes</starplayers>   
        
        <add_assistant>20000</add_assistant>
        <add_cheerleaders>20000</add_cheerleaders>
        <weather_wizard>30000</weather_wizard>
        <horacio_x_schottenheim>80000</horacio_x_schottenheim>
    </inducements>
    <playertypes>               
        <playerType>
            <limit>4</limit>
            <position>Blitzer</position>
            <movement>7</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Block</skill>
                <skill>Catch</skill>
                <skill>Dauntless</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </single>            
            <double>               
                <skillType>Strength</skillType>                              
            </double>
        </playerType>
        <playerType>
            <limit>4</limit>
            <position>Yeomen</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Wrestle</skill>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
            </single>
            <double>
                <skillType>Pass</skillType>
                <skillType>Agility</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Lineman</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>2</agility>
            <armor>7</armor>
            <skills>
                <skill>Fend</skill>
            </skills>
            <cost>40000</cost>
            <single>
                <skillType>General</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>Strength</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>               
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/lrb4/necromantics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>
    <inducements></inducements>
    <name>NecromanticKey</name>
    <reroll>70000</reroll>
    <apothecary>false</apothecary>
    <chef>300000</chef>
    <igor>true</igor>
    <bribe>100000</bribe>
    <max_big_guy>1</max_big_guy>
    <playertypes>               
        <playerType>
            <limit>2</limit>
            <position>Werewolf</position>
            <movement>8</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Frenzy</skill>
                <skill>Catch</skill>
                <skill>Claw</skill>
            </skills>
            <cost>120000</cost>
            <single>
                <skillType>General Skill</skillType>
                <skillType>Agility Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Agility Trait</skillType>
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Ghoul</position>
            <movement>7</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>7</armor>
            <skills>
                <skill>Dodge</skill>
            </skills>
            <cost>70000</cost>
            <single>
                <skillType>General Skill</skillType>
                <skillType>Agility Skill</skillType>
            </single>
            <double>
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>General Trait</skillType>
                <skillType>Agility Trait</skillType>
            </double>
        </playerType>
        <playerType>
             <limit>2</limit>
            <position>Wight</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Block</skill>
                <skill>Regeneration</skill>
            </skills>
            <cost>90000</cost>
            <single>
                <skillType>General Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>Agility Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>2</limit>
            <position>Flesh Golem</position>
            <movement>4</movement>
            <strength>4</strength>
            <agility>2</agility>
            <armor>9</armor>
            <skills>
                <skill>Stand Firm</skill>
                <skill>Regeneration</skill>
            </skills>
            <cost>110000</cost>
            <single>
                <skillType>General Skill</skillType>
                <skillType>Strength Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Strength Trait</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>Agility Skill</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>12</limit>
            <position>Zombie</position>
            <movement>4</movement>
            <strength>3</strength>
            <agility>2</agility>
            <armor>8</armor>
            <skills>
                <skill>Regeneration</skill>
            </skills>
            <cost>30000</cost>
            <single>
                <skillType>General Skill</skillType>
            </single>
            <double>
                <skillType>General Trait</skillType>
                <skillType>Strength Skill</skillType>
                <skillType>Pass Skill</skillType>
                <skillType>Agility Skill</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>

=== Bojo38/tourma/src/teamma/rules/BB2016/chaos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="roster.xsl"?>

<rostertype xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
            xsi:noNamespaceSchemaLocation='roster.xsd'>

    <name>ChaosChosenKey</name>
    <reroll>60000</reroll>
    <apothecary>true</apothecary>
    
    <inducements>
        <chef>300000</chef>
        <bribe>100000</bribe>
        <babes>50000</babes>
        <wizard>150000</wizard>
        <reroll>100000</reroll>
        <apothecary>100000</apothecary>

        <cards>yes</cards>
        <starplayers>yes</starplayers>   
        
        <add_assistant>20000</add_assistant>
        <add_cheerleaders>20000</add_cheerleaders>
        <weather_wizard>30000</weather_wizard>
        
        <chaos_wizard>150000</chaos_wizard>
        <horticulturalist>150000</horticulturalist>
        <papa_skullbones>80000</papa_skullbones>
        <horacio_x_schottenheim>80000</horacio_x_schottenheim>
    </inducements>
            
    <playertypes>               
        <playerType>
            <limit>4</limit>
            <position>Chaos Warrior</position>
            <movement>5</movement>
            <strength>4</strength>
            <agility>3</agility>
            <armor>9</armor>
            <skills>
            </skills>
            <cost>100000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>16</limit>
            <position>Beastman</position>
            <movement>6</movement>
            <strength>3</strength>
            <agility>3</agility>
            <armor>8</armor>
            <skills>
                <skill>Horns</skill>              
            </skills>
            <cost>60000</cost>
            <single>
                <skillType>General</skillType>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
        <playerType>
            <limit>1</limit>
            <position>Minotaur</position>
            <movement>5</movement>
            <strength>5</strength>
            <agility>2</agility>
            <armor>8</armor>
            <skills>
                <skill>Loner</skill>
                <skill>Wild Animal</skill>
                <skill>Mighty Blow</skill>
                <skill>Thick Skull</skill>
                <skill>Frenzy</skill>
                <skill>Horns</skill>              
            </skills>
            <cost>150000</cost>
            <single>
                <skillType>Strength</skillType>
                <skillType>Mutation</skillType>
            </single>
            <double>
                <skillType>General</skillType>
                <skillType>Agility</skillType>
                <skillType>Pass</skillType>
            </double>
        </playerType>
    </playertypes>
</rostertype>
